// Code generated by MockGen. DO NOT EDIT.
// Source: logger.go

// Package http is a generated GoMock package.
package http

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockLogger is a mock of Logger interface
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Info mocks base method
func (m *MockLogger) Info(info string, extra map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", info, extra)
}

// Info indicates an expected call of Info
func (mr *MockLoggerMockRecorder) Info(info, extra interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), info, extra)
}

// Warn mocks base method
func (m *MockLogger) Warn(info string, extra map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", info, extra)
}

// Warn indicates an expected call of Warn
func (mr *MockLoggerMockRecorder) Warn(info, extra interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), info, extra)
}

// Error mocks base method
func (m *MockLogger) Error(err error, extra map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", err, extra)
}

// Error indicates an expected call of Error
func (mr *MockLoggerMockRecorder) Error(err, extra interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), err, extra)
}

// Fatal mocks base method
func (m *MockLogger) Fatal(err error, extra map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatal", err, extra)
}

// Fatal indicates an expected call of Fatal
func (mr *MockLoggerMockRecorder) Fatal(err, extra interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), err, extra)
}
